insert into weathers(id,date,location)values(0,'2021-01-27','{"lat": 2.0223,"lon": 2.3349,"city": "Dallas","state": "Texas"}');
insert into weathers(id,date,location)values(1,'2021-01-28','{"lat": 2.0223,"lon": 2.3349,"city": "Dallas","state": "Texas"}');
insert into weathers(id,date,location)values(2,'2021-01-29','{"lat": 2.0223,"lon": 2.3349,"city": "Dallas","state": "Texas"}');
insert into weathers(id,date,location)values(3,'2021-01-30','{"lat": 2.0223,"lon": 2.3349,"city": "Dallas","state": "Texas"}');
insert into weathers(id,date,location)values(4,'2021-01-31','{"lat": 2.0223,"lon": 2.3349,"city": "Dallas","state": "Texas"}');
insert into weather_temperature(weather_id,temperature)values(0,1.0);
insert into weather_temperature(weather_id,temperature)values(0,31.0);
insert into weather_temperature(weather_id,temperature)values(0,12.0);
insert into weather_temperature(weather_id,temperature)values(0,14.0);
insert into weather_temperature(weather_id,temperature)values(0,15.0);
insert into weather_temperature(weather_id,temperature)values(0,12.0);
insert into weather_temperature(weather_id,temperature)values(0,15.0);
insert into weather_temperature(weather_id,temperature)values(1,1.0);
insert into weather_temperature(weather_id,temperature)values(1,31.0);
insert into weather_temperature(weather_id,temperature)values(1,12.0);
insert into weather_temperature(weather_id,temperature)values(1,14.0);
insert into weather_temperature(weather_id,temperature)values(1,15.0);
insert into weather_temperature(weather_id,temperature)values(1,12.0);
insert into weather_temperature(weather_id,temperature)values(1,15.0);
